# Generated by Django 4.2.7 on 2026-03-21 20:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Filiere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('duree', models.PositiveIntegerField(help_text='Durée en années')),
                ('description', models.TextField(blank=True)),
                ('debouches', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Filière',
                'verbose_name_plural': 'Filières',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='Matiere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=20, unique=True)),
            ],
            options={
                'verbose_name': 'Matière',
                'verbose_name_plural': 'Matières',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='SerieBac',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True)),
                ('nom', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Série de Bac',
                'verbose_name_plural': 'Séries de Bac',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Universite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('ville', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('est_publique', models.BooleanField(default=True)),
                ('site_web', models.URLField(blank=True)),
            ],
            options={
                'verbose_name': 'Université',
                'verbose_name_plural': 'Universités',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='FiliereSerie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filiere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orienta.filiere')),
                ('serie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orienta.seriebac')),
            ],
            options={
                'verbose_name': 'Série Acceptée par Filière',
                'verbose_name_plural': 'Séries Acceptées par Filière',
                'unique_together': {('filiere', 'serie')},
            },
        ),
        migrations.CreateModel(
            name='FiliereMatiere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordre', models.IntegerField(choices=[(1, 'Priorité 1'), (2, 'Priorité 2'), (3, 'Priorité 3')])),
                ('filiere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='filiere_matieres', to='orienta.filiere')),
                ('matiere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orienta.matiere')),
            ],
            options={
                'verbose_name': 'Matière Prioritaire de Filière',
                'verbose_name_plural': 'Matières Prioritaires de Filière',
                'ordering': ['ordre'],
                'unique_together': {('filiere', 'ordre')},
            },
        ),
        migrations.AddField(
            model_name='filiere',
            name='matieres_prioritaires',
            field=models.ManyToManyField(related_name='filieres', through='orienta.FiliereMatiere', to='orienta.matiere'),
        ),
        migrations.AddField(
            model_name='filiere',
            name='series_acceptees',
            field=models.ManyToManyField(related_name='filieres', through='orienta.FiliereSerie', to='orienta.seriebac'),
        ),
        migrations.CreateModel(
            name='UniversiteFiliere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annee', models.PositiveIntegerField(default=2024)),
                ('seuil_minimum', models.FloatField(help_text='Note minimale pour admission (payant)')),
                ('seuil_demi_bourse', models.FloatField(help_text='Note minimale pour demi-bourse')),
                ('seuil_bourse', models.FloatField(help_text='Note minimale pour bourse complète')),
                ('places_disponibles', models.PositiveIntegerField(default=0)),
                ('filiere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='universite_filieres', to='orienta.filiere')),
                ('universite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='universite_filieres', to='orienta.universite')),
            ],
            options={
                'verbose_name': 'Filière par Université',
                'verbose_name_plural': 'Filières par Université',
                'unique_together': {('universite', 'filiere', 'annee')},
            },
        ),
        migrations.CreateModel(
            name='SerieMatiere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coefficient', models.PositiveIntegerField(default=1)),
                ('matiere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='serie_matieres', to='orienta.matiere')),
                ('serie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='serie_matieres', to='orienta.seriebac')),
            ],
            options={
                'verbose_name': 'Matière par Série',
                'verbose_name_plural': 'Matières par Série',
                'unique_together': {('serie', 'matiere')},
            },
        ),
    ]
